name: Rust Checker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: |
            target
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Run rust_checker
        run: cargo run -- .

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: rust_checker_report
          path: target/report.html

